### PR TITLE
Fix generic webkit browser to show local file upload dialog

### PR DESCRIPTION
**Pull request by kicktheken**
This fixes the local file upload dialog when used inside the Mac Office Outlook addin. This changes are cherry picked from this commit: https://github.com/moxiecode/moxie/commit/101494d

### CODE REVIEW

**Review by ns-chihchen — APPROVED** [review]
lgtm 
Thanks for your contributions.

**Comment by vinodc** [comment]
Thanks for the contribution Kenneth! Kloudless team, please feel free to merge this in and include it on the next release.

**Comment by kicktheken** [comment]
It looks like these changes were not updated with the change to putting `moxie` in a separate module (https://github.com/Kloudless/file-picker-plupload-module). Is it possible to update the changes in this PR to there?

**Comment by ns-vchandru** [comment]
Thanks for pointing this out Kenneth. I'll track this in a support ticket.

**Comment by ueewbd** [comment]
Hi @kicktheken 

We've released v2.6.4 to apply your improvements. 
Sorry for the inconvenience.

**Pull request merged**
